model:
  checkpoint: "BAAI/bge-m3"
  query_maxlen: 128
  doc_maxlen: 2048
  embedding_dim: 768

data:
  raw_input_dir: "data/database_wikipedia"
  processed_passage_path: "data/processed/wiki_passages.jsonl"
  passage_max_words: 2048
  passage_overlap_words: 128

indexing:
  index_save_path: "data/index/wikipedia_colbert.faiss"
  embedding_save_path: "data/index/doc_embedding.npy"
  passage_map_save_path: "data/index/passage_map.json" # passage_id -> text
  embedding_map_save_path: "data/index/embedding_to_passage_map.pkl" # embedding_idx -> passage_id

  faiss_nlist: 1024
  faiss_m: 16
  faiss_nbits: 8

  faiss_add_chunk_size_embedding: 10000

  faiss_train_sample_size: 100000
  batch_size: 16

retrieval:
  faiss_nprobe: 16
  candidate_k: 1000
  top_n: 10

general:
  device: "cuda"
